baseURL = "https://sander.saares.eu/"
languageCode = "en-us"
title = "Sander Saares"
theme = "saares"

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[params]
# Blog subtitle which appears below blog title. Supports markdown.
subtitle = "Thoughts that might prove useful"
# Number of posts to show in recent posts list (Optional). Defaults to 10.
recentPostsCount = 10
# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
excludedTypes = ["page"]
# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
featherIconsCDN = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All articles"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/sandersaares"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/sandersaares"

# Enable tags.
[taxonomies]
tag = "tags"