baseURL = "https://sander.saares.eu/"
languageCode = "en-us"
title = "Website of Sander Saares"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-139852049-1"

[params]
recentPostsCount = 6

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About Me"
url = "/about"
weight = 2

[[menu.main]]
name = "All Articles"
url = "/articles"
weight = 3

[[menu.main]]
name = "By Category"
url = "/categories"
weight = 4

[taxonomies]
category = "categories"