# based on ezhil theme

name = "saares"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = []
features = []
min_version = "0.0"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
